### ISSUE TITLE
no module found 'react-icons/lib/fa/table'

### ISSUE THREAD

**Issue by shikhar022** [eemp/mozaik-ext-table#3]
TableIcon is not working with newer versions of  react-icons dependency. Apparently It has changed the way it recommends imports. Please help here

**Comment by eemp** [comment]
Addressed with https://github.com/eemp/mozaik-ext-table/pull/4.  The problem was again a missing module - I have no idea what I was doing back when I published this package :(

However, I updated eslint configuration to report on missing packages, so hopefully this is the last of such issues.

Released a patch fix `mozaik-ext-table@0.1.1`.  Mind giving that a shot?

**Comment by shikhar022** [comment]
Thanks for your prompt support! I would love to get in touch with you. I have some questions around mozaik. Lets connect if possible

**Comment by eemp** [comment]
I haven't really touched mozaik in over a year and a half :(  It was really the only modular / plugin based option I saw to quickly create dashboards at the time with notable traction.  I haven't had to work on something like that since.
